// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_asp.data;

#nullable disable

namespace Projetasp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221220194244_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet_asp.Models.Chef", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("datenaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("prenom")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("specialite")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("tel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Chefs", "Chefs1");
                });

            modelBuilder.Entity("Projet_asp.Models.Contact", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Projet_asp.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<double>("prix")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus", "Menu1");
                });

            modelBuilder.Entity("Projet_asp.Models.Plat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("id_Menu")
                        .HasColumnType("int");

                    b.Property<string>("lib")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("id_Menu");

                    b.ToTable("Plats", "Plats1");
                });

            modelBuilder.Entity("Projet_asp.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Heure")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nom_client")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("email_client")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("nombre_de_personne")
                        .HasColumnType("int");

                    b.Property<string>("prenom_client")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<int>("tel_client")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Reservations", "RES1");
                });

            modelBuilder.Entity("Projet_asp.Models.Plat", b =>
                {
                    b.HasOne("Projet_asp.Models.Menu", "Menu")
                        .WithMany()
                        .HasForeignKey("id_Menu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
